apiVersion: batch/v1
kind: CronJob
metadata:
  name: date-cronjob
spec:
  schedule: "*/5 * * * *"  # S'exécute toutes les 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-date
            image: busybox
            command:
            - /bin/sh
            - -c
            - date
          restartPolicy: OnFailure
