apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: middle
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/kubernetes/wordpress"
  storageClassName: manual